# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Halecs/Desktop/Buscaminas/Buscaminas

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Halecs/Desktop/Buscaminas/Buscaminas

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Halecs/Desktop/Buscaminas/Buscaminas/CMakeFiles /mnt/c/Users/Halecs/Desktop/Buscaminas/Buscaminas/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Halecs/Desktop/Buscaminas/Buscaminas/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PrincipalCliente

# Build rule for target.
PrincipalCliente: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PrincipalCliente
.PHONY : PrincipalCliente

# fast build rule for target.
PrincipalCliente/fast:
	$(MAKE) -f CMakeFiles/PrincipalCliente.dir/build.make CMakeFiles/PrincipalCliente.dir/build
.PHONY : PrincipalCliente/fast

#=============================================================================
# Target rules for targets named PrincipalServidor

# Build rule for target.
PrincipalServidor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PrincipalServidor
.PHONY : PrincipalServidor

# fast build rule for target.
PrincipalServidor/fast:
	$(MAKE) -f CMakeFiles/PrincipalServidor.dir/build.make CMakeFiles/PrincipalServidor.dir/build
.PHONY : PrincipalServidor/fast

Buscaminas.o: Buscaminas.cpp.o
.PHONY : Buscaminas.o

# target to build an object file
Buscaminas.cpp.o:
	$(MAKE) -f CMakeFiles/PrincipalServidor.dir/build.make CMakeFiles/PrincipalServidor.dir/Buscaminas.cpp.o
.PHONY : Buscaminas.cpp.o

Buscaminas.i: Buscaminas.cpp.i
.PHONY : Buscaminas.i

# target to preprocess a source file
Buscaminas.cpp.i:
	$(MAKE) -f CMakeFiles/PrincipalServidor.dir/build.make CMakeFiles/PrincipalServidor.dir/Buscaminas.cpp.i
.PHONY : Buscaminas.cpp.i

Buscaminas.s: Buscaminas.cpp.s
.PHONY : Buscaminas.s

# target to generate assembly for a file
Buscaminas.cpp.s:
	$(MAKE) -f CMakeFiles/PrincipalServidor.dir/build.make CMakeFiles/PrincipalServidor.dir/Buscaminas.cpp.s
.PHONY : Buscaminas.cpp.s

Partida.o: Partida.cpp.o
.PHONY : Partida.o

# target to build an object file
Partida.cpp.o:
	$(MAKE) -f CMakeFiles/PrincipalServidor.dir/build.make CMakeFiles/PrincipalServidor.dir/Partida.cpp.o
.PHONY : Partida.cpp.o

Partida.i: Partida.cpp.i
.PHONY : Partida.i

# target to preprocess a source file
Partida.cpp.i:
	$(MAKE) -f CMakeFiles/PrincipalServidor.dir/build.make CMakeFiles/PrincipalServidor.dir/Partida.cpp.i
.PHONY : Partida.cpp.i

Partida.s: Partida.cpp.s
.PHONY : Partida.s

# target to generate assembly for a file
Partida.cpp.s:
	$(MAKE) -f CMakeFiles/PrincipalServidor.dir/build.make CMakeFiles/PrincipalServidor.dir/Partida.cpp.s
.PHONY : Partida.cpp.s

PrincipalCliente.o: PrincipalCliente.cpp.o
.PHONY : PrincipalCliente.o

# target to build an object file
PrincipalCliente.cpp.o:
	$(MAKE) -f CMakeFiles/PrincipalCliente.dir/build.make CMakeFiles/PrincipalCliente.dir/PrincipalCliente.cpp.o
.PHONY : PrincipalCliente.cpp.o

PrincipalCliente.i: PrincipalCliente.cpp.i
.PHONY : PrincipalCliente.i

# target to preprocess a source file
PrincipalCliente.cpp.i:
	$(MAKE) -f CMakeFiles/PrincipalCliente.dir/build.make CMakeFiles/PrincipalCliente.dir/PrincipalCliente.cpp.i
.PHONY : PrincipalCliente.cpp.i

PrincipalCliente.s: PrincipalCliente.cpp.s
.PHONY : PrincipalCliente.s

# target to generate assembly for a file
PrincipalCliente.cpp.s:
	$(MAKE) -f CMakeFiles/PrincipalCliente.dir/build.make CMakeFiles/PrincipalCliente.dir/PrincipalCliente.cpp.s
.PHONY : PrincipalCliente.cpp.s

PrincipalServidor.o: PrincipalServidor.cpp.o
.PHONY : PrincipalServidor.o

# target to build an object file
PrincipalServidor.cpp.o:
	$(MAKE) -f CMakeFiles/PrincipalServidor.dir/build.make CMakeFiles/PrincipalServidor.dir/PrincipalServidor.cpp.o
.PHONY : PrincipalServidor.cpp.o

PrincipalServidor.i: PrincipalServidor.cpp.i
.PHONY : PrincipalServidor.i

# target to preprocess a source file
PrincipalServidor.cpp.i:
	$(MAKE) -f CMakeFiles/PrincipalServidor.dir/build.make CMakeFiles/PrincipalServidor.dir/PrincipalServidor.cpp.i
.PHONY : PrincipalServidor.cpp.i

PrincipalServidor.s: PrincipalServidor.cpp.s
.PHONY : PrincipalServidor.s

# target to generate assembly for a file
PrincipalServidor.cpp.s:
	$(MAKE) -f CMakeFiles/PrincipalServidor.dir/build.make CMakeFiles/PrincipalServidor.dir/PrincipalServidor.cpp.s
.PHONY : PrincipalServidor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... PrincipalCliente"
	@echo "... PrincipalServidor"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Buscaminas.o"
	@echo "... Buscaminas.i"
	@echo "... Buscaminas.s"
	@echo "... Partida.o"
	@echo "... Partida.i"
	@echo "... Partida.s"
	@echo "... PrincipalCliente.o"
	@echo "... PrincipalCliente.i"
	@echo "... PrincipalCliente.s"
	@echo "... PrincipalServidor.o"
	@echo "... PrincipalServidor.i"
	@echo "... PrincipalServidor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

